// <auto-generated />
namespace XXX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Regex_Adjusted_For_FirstName_And_LastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Regex_Adjusted_For_FirstName_And_LastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201611300439097_Regex_Adjusted_For_FirstName_And_LastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
